epochs: 40
out_res: 128
resume: 0 # Which epoch to resume from. 0 means starting at epoch 1 (epochs are 1-indexed)
latent_size: 512
lr: 1e-4
lambd: 10
cuda: True
ddp: 
  enabled: False
  world_size: 1
  rank: 0
data_dir: "./dataset/"
checkpoint_dir: "./ckpt/"
output_dir: "./output"
weight_dir: "./weight/"
schedule:
  - start_epoch: 5
    batch_size: 16
    grow_epochs: 5
  - start_epoch: 15
    batch_size: 16 
    grow_epochs: 5
  - start_epoch: 25
    batch_size: 16
    grow_epochs: 5
  - start_epoch: 35
    batch_size: 8
    grow_epochs: 2
  - start_epoch: 40
    batch_size: 4 
    grow_epochs: 1

