epochs: 45
out_res: 128
resume: 0 # Which epoch to resume from. 0 means starting at epoch 1 (epochs are 1-indexed)
latent_size: 512
num_workers: 5
lr: 1e-3
lambd: 10
cuda: True
wandb: 
  enabled: True
  save_code: True
  init:
    project: 'pggan'
    mode: online
n_discrim: 1
ddp: True
data_dir: "./dataset/"
checkpoint_dir: "./ckpt/"
output_dir: "./output"
weight_dir: "./weight/"
schedule:
  - start_epoch: 1 # 4x4
    batch_size: 256
    grow_epochs: 0
  - start_epoch: 5 # 8x8
    batch_size: 256
    grow_epochs: 5
  - start_epoch: 15 # 16x16
    batch_size: 128
    grow_epochs: 5
  - start_epoch: 25 # 32x32
    batch_size: 32
    grow_epochs: 5
  - start_epoch: 35 # 64x64
    batch_size: 16
    grow_epochs: 2
  - start_epoch: 40 # 128x128
    batch_size: 8
    grow_epochs: 1

