epochs: 120
out_res: 128
resume: 0 # Which epoch to resume from. 0 means starting at epoch 1 (epochs are 1-indexed)
latent_size: 512
num_workers: 5
lr: 1e-3
lambd: 10
cuda: True
wandb: 
  enabled: True
  save_code: True
  init:
    project: 'pggan'
    mode: online
n_discrim: 1
ddp: True
data_dir: "./dataset/"
checkpoint_dir: "./ckpt/"
output_dir: "./output"
weight_dir: "./weight/"
schedule:
  - start_epoch: 1 # 4x4
    batch_size: 16
    grow_epochs: 0
  - start_epoch: 30 # 8x8
    batch_size: 16
    grow_epochs: 30
  - start_epoch: 90 # 16x16
    batch_size: 16
    grow_epochs: 30
  - start_epoch: 150 # 32x32
    batch_size: 16
    grow_epochs: 30
  - start_epoch: 210 # 64x64
    batch_size: 16
    grow_epochs: 30
  - start_epoch: 270 # 128x128
    batch_size: 16
    grow_epochs: 30

